### ISSUE TITLE
Through the roof!

### ISSUE THREAD

**Issue by Dijker** [robertklep/name.klep.transitions#3]
Version 1.02 beta from store
0-1,100s,3s
=>> 0.99, 1.02 ...... 3.xx

**Comment by robertklep** [comment]
Found the issue, but in order to fix it I'd like some feedback.

The root of the problem is that 100s isn't cleanly divisible by 3s: the timer reaches 99s, and then what should it do?

A few options:
* instead of waiting 3 more seconds, only wait one second?
* emit the end value at 99s?
* emit the end value at 102s?
* emit the end value at the closest value to 100s divisible by 3, so in this case as 99s?

Not sure what the best solution would be. Right now, with a quick fix, it will be the latter (it emits the end value as 102s).

**Comment by Dijker** [comment]
Although in seconds and dimming I would not care, 
thinking of minutes  or time critical usage it would be best  to  wait the remaining 1 second. But I see the coding issue. 
Most important is not continue after you passed the max. 
But  even the stop at 99 could be.

**Comment by robertklep** [comment]
For time critical usage, the best bet would be to make the duration divisible by the step value. I'll add some extra text to the README to explain this.

The main issue is indeed that the timer should stop ;)

**Comment by robertklep** [comment]
Just published v1.0.3 which hopefully solved this problem.
